linters:
  enable-all: true
  disable:
    - wsl
    - maligned
    - nlreturn
    - varnamelen
    - gochecknoglobals
    - exhaustivestruct
    - exhaustruct
    - cyclop
    - gocognit
    - godox
    - funlen

linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
